package execution.scenarios;

import com.intuit.karate.Results;
import com.intuit.karate.Runner;
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * KarateTestSuite is the main class to run all Karate tests and generate
 * detailed reports in HTML and JSON formats.
 * <p>
 * It uses JUnit 5 for test execution and Cucumber Reporting to provide a
 * professional presentation of test results.
 * </p>
 * <p>
 * Key features:
 * <ul>
 * <li>Sequential or parallel execution of Karate tests.</li>
 * <li>Automatic generation of HTML and JSON reports.</li>
 * <li>Automatic verification of failed tests to ensure execution success.</li>
 * </ul>
 * </p>
 *
 * @author Zied HANNACHI
 * @version 1.0
 * @since 2025-11-16
 */
public class KarateTestSuite {

	/**
	 * Executes all tests located in the <code>classpath:features</code> folder.
	 * <p>
	 * This method performs the following steps:
	 * <ol>
	 * <li>Runs Karate tests with JSON output for reporting.</li>
	 * <li>Generates a detailed HTML report using
	 * {@link #generateReport(String)}.</li>
	 * <li>Verifies that there are no failed tests and triggers an assertion if
	 * there are any.</li>
	 * </ol>
	 * </p>
	 */
	@Test
	public void testParallel() {

		// Karate execution
		Results results = Runner.path("classpath:features").outputCucumberJson(true).parallel(1);

		// Generate report
		generateReport(results.getReportDir());

		// Verification
		assertEquals(0, results.getFailCount(), results.getErrorMessages());
	}

	/**
	 * Generates a Cucumber HTML report from the JSON files produced by Karate.
	 *
	 * @param karateOutputPath The path to the folder containing the JSON files
	 *                         generated by Karate. Typically:
	 *                         <code>target/karate-reports</code>
	 */
	public static void generateReport(String karateOutputPath) {
		Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] { "json" }, true);

		List<String> jsonPaths = new ArrayList<>(jsonFiles.size());
		jsonFiles.forEach(f -> jsonPaths.add(f.getAbsolutePath()));

		Configuration config = new Configuration(new File("target"), "Karate-API-Report");
		ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
		reportBuilder.generateReports();
	}
}